
DROP TABLE tjF0mat;
DROP TABLE tjF1mat;
DROP TABLE tjF2mat;
DROP TABLE tjF3mat;
DROP TABLE tjF4mat;
DROP TABLE tjF5mat;
DROP TABLE tjF6mat;
DROP TABLE tjF7mat;
DROP TABLE tjF8mat;

DROP TABLE zjkF0mat;
DROP TABLE zjkF1mat;
DROP TABLE zjkF2mat;
DROP TABLE zjkF3mat;
DROP TABLE zjkF4mat;
DROP TABLE zjkF5mat;
DROP TABLE zjkF6mat;
DROP TABLE zjkF7mat;
DROP TABLE zjkF8mat;

DROP TABLE tsF0mat;
DROP TABLE tsF1mat;
DROP TABLE tsF2mat;
DROP TABLE tsF3mat;
DROP TABLE tsF4mat;
DROP TABLE tsF5mat;
DROP TABLE tsF6mat;
DROP TABLE tsF7mat;
DROP TABLE tsF8mat;